FROM golang:1.26.0-alpine AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 go build -o /out/nereid-controller ./cmd/nereid-controller

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/nereid-controller /nereid-controller
ENTRYPOINT ["/nereid-controller"]
