apiVersion: nereid.yuiseki.net/v1alpha1
kind: Work
metadata:
  name: codex-cli-smoke
spec:
  kind: agent.cli.v1
  title: "OpenAI Codex CLI smoke test"
  agent:
    image: node:22-bookworm-slim
    command:
      - npx
      - -y
      - "@openai/codex"
      - --help
  constraints:
    deadlineSeconds: 900
  artifacts:
    layout: files
